VERSION = "v2"

COLOR_RED = "#FF0000"
COLOR_BLUE = "#0000FF"
COLOR_GREY = "#808080"
COLOR_HIGHTLIGHT = "#FFC910"

KEY_DOWN = '3'
KEY_UP = '0'
KEY_RIGHT = '2'
KEY_LEFT = '1'
KEY_SELECT = '4'
KEY_CONTINUE = 'c'
KEY_ABORT = 'q'
KEY_RETURN = 'r'

KEY_1 = '1'
KEY_2 = '2'
KEY_3 = '3'
COLOR_1 = "red"
COLOR_2 = "blue"
COLOR_3 = "green"