VERSION = "v1"

COLOR_RED = "#FF0000"
COLOR_BLUE = "#0000FF"
COLOR_GREY = "#808080"
COLOR_HIGHTLIGHT = "#FFC910"

KEY_UP = 'w'
KEY_DOWN = 's'
KEY_LEFT = 'a'
KEY_RIGHT = 'd'
KEY_SELECT = '1'
KEY_ABORT = 'q'